### ISSUE TITLE
ZBDBench fails in `rocksdb_overwrite`

### ISSUE THREAD

**Issue by metaspace** [westerndigitalcorporation/zenfs#165]
The following command fail:
```bash
db_bench  --fs_uri=zenfs://dev:nvme0n2 --key_size=20 --value_size=800 --target_file_size_base=2084999004160 --write_buffer_size=2147483648 --max_bytes_for_level_base=4294967296 --max_bytes_for_level_multiplier=4 --max_background_jobs=8 --max_background_compactions=8 --use_direct_io_for_flush_and_compaction --stats_dump_period_sec=15 --delete_obsolete_files_period_micros=3000000 --statistics --benchmarks=overwrite,stats --use_existing_db --num=165000000 --duration=7200
```
It prints
```text
RocksDB:    version 6.25
Date:       Sun Mar  6 03:16:57 2022
CPU:        32 * AMD EPYC-Rome Processor
CPUCache:   512 KB
... finished 100 ops                              ^M... finished 200 ops                              ^M... finished 300 ops                              ^M... finished 400 ops                            >

Initializing RocksDB Options from the specified file
Initializing RocksDB Options from command-line flags
Keys:       20 bytes each (+ 0 bytes user-defined timestamp)
Values:     800 bytes each (400 bytes after compression)
Entries:    165000000
Prefix:    0 bytes
Keys per prefix:    0
RawSize:    129032.1 MB (estimated)
FileSize:   66089.6 MB (estimated)
Write rate: 0 bytes/second
Read rate: 0 ops/second
Compression: Snappy
Compression sampling rate: 0
Memtablerep: SkipListFactory
Perf Level: 1
------------------------------------------------
DB path: [rocksdbtest/dbbench]
```
and then the command exits with exit status 1.

The test is executed on a 1TB `WZS4C8T1TDSP303`. Before the overwrite, `rocksdb_fillrandom` completes without error.

Full test sequence output:
```text
ZenFS file system created. Free space: 970377 MB
Output directory: /rocks/work/results/zbdbench/2022-03-05-210836
Check OK: /dev/nvme0n2 is valid
Check OK: /dev/nvme0n2 is not mounted
Check OK: /dev/nvme0n2 is set with 'mq-deadline' scheduler
Check OK: /dev/nvme0n2 is a zoned block device
Required host tools: {'blkdiscard', 'db_bench', 'blkzone', 'zenfs'}
Check OK: All executables available

Benchmarks:
  rocksdb_fillprep
  rocksdb_overwrite
  rocksdb_readwhilewriting

Dev: /dev/nvme0n2
Env: system
Output: /rocks/work/results/zbdbench/2022-03-05-210836

Executing: rocksdb_fillprep
Exec:  zenfs mkfs --zbd=nvme0n2 --finish_threshold=20 --aux_path=/tmp/zenfs_aux
Exec:  db_bench  --fs_uri=zenfs://dev:nvme0n2 --key_size=20 --value_size=800 --target_file_size_base=2084999004160 --write_buffer_size=2147483648 --max_bytes_for_level_base=4294967296 --max_bytes_for_level_multiplier=4 --max_background_jobs=8 --max_background_compactions=8 --use_direct_io_for_flush_and_compaction --stats_dump_period_sec=15 --delete_obsolete_files_period_micros=3000000 --statistics --benchmarks=fillrandom,stats --num=1650000000 > /rocks/work/results/zbdbench/2022-03-05-210836/rocksdb_fillprep.txt 2>&1
  Output written to: /rocks/work/results/zbdbench/2022-03-05-210836/rocksdb.csv
Not implemented (plot)
Executing: rocksdb_overwrite
Exec:  db_bench  --fs_uri=zenfs://dev:nvme0n2 --key_size=20 --value_size=800 --target_file_size_base=2084999004160 --write_buffer_size=2147483648 --max_bytes_for_level_base=4294967296 --max_bytes_for_level_multiplier=4 --max_background_jobs=8 --max_background_compactions=8 --use_direct_io_for_flush_and_compaction --stats_dump_period_sec=15 --delete_obsolete_files_period_micros=3000000 --statistics --benchmarks=overwrite,stats --use_existing_db --num=165000000 --duration=7200 > /rocks/work/results/zbdbench/2022-03-05-210836/rocksdb_overwrite.txt 2>&1
```

Traceback for zbdbench:
```text
python3 /rocks/dest/zbdbench/run.py -c system -b rocksdb_fillprep rocksdb_overwrite rocksdb_readwhilewriting -o /rocks/work/results/zbdbench -d /dev/nvme0n2
Traceback (most recent call last):
  File "/rocks/dest/zbdbench/run.py", line 246, in <module>
    main(sys.argv[1:])
  File "/rocks/dest/zbdbench/run.py", line 241, in main
    run_benchmarks(dev, container, benches, run_output)
  File "/rocks/dest/zbdbench/run.py", line 133, in run_benchmarks
    b.run(dev, container)
  File "/rocks/dest/zbdbench/benchs/rocksdb.py", line 153, in run
    self.run_cmd(dev, container, 'db_bench', self.get_run_string(dev, bench_params, self.jobname))
  File "/rocks/dest/zbdbench/benchs/base.py", line 134, in run_cmd
    subprocess.check_call(cmd, shell=True)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command ' db_bench  --fs_uri=zenfs://dev:nvme0n2 --key_size=20 --value_size=800 --target_file_size_base=2084999004160 --write_buffer_size=2147483648 --max_bytes_for_level_base=4294967296 --max_bytes_for_level_multiplier=4 --max_background_jobs=8 --max_background_compactions=8 --use_direct_io_for_flush_and_compaction --stats_dump_period_sec=15 --delete_obsolete_files_period_micros=3000000 --statistics --benchmarks=overwrite,stats --use_existing_db --num=165000000 --duration=7200 > /rocks/work/results/zbdbench/2022-03-05-210836/rocksdb_overwrite.txt 2>&1' returned non-zero exit status 1.
```

**Comment by aravind-wdc** [comment]
I ran the exact same test (except using rocksdb 7.0 and a 4TB drive) and it passed.
`sudo ./db_bench  --fs_uri=zenfs://dev:nvme0n1 --key_size=20 --value_size=800 --target_file_size_base=2084999004160 --w
rite_buffer_size=2147483648 --max_bytes_for_level_base=4294967296 --max_bytes_for_level_multiplier=4 --max_background_jobs=8 --max_background_compactions=8 --use_direct_io_for_
flush_and_compaction --stats_dump_period_sec=15 --delete_obsolete_files_period_micros=3000000 --statistics --benchmarks=overwrite,stats --use_existing_db --num=165000000 --dura
tion=7200`

Also, target_file_size_base is set as 2TB, is it deliberate ?
I see that it failed on Rocksdb v6.25, need to check if something got fixed in 7.0.

**Comment by yhr** [comment]
@aravind-wdc : Just to double-check, did you create the file system with "zenfs mkfs --zbd=nvme0n2 --finish_threshold=20 --aux_path=/tmp/zenfs_aux" ? 

I've run lots of testing lately and have not seen any issues with master, but I normally run finish thresholds these days.

**Comment by aravind-wdc** [comment]
Yes. This is what I used to do mkfs.
`sudo ./zenfs mkfs --zbd=nvme0n1 --aux_path=/tmp/zaux1/ --finish_threshold=0 --force`

Just to clarify, my understanding is that this issue is reported on 6.25. But I ran the same test on 7.0 and did not hit the issue.

**Comment by metaspace** [comment]
It is sort of odd that it just exits without an error message. It did not core dump or anything, a normal exit with return code 1.

**Comment by yhr** [comment]
I ran the workload manually, and it completed with exit code 0 on a 2TB drive (with finish treshhold set to 20%)

The 2TB target file size results in a wierd set of files though.

```
    13343708	Mar 08 2022 16:54:15            LOG                             
           0	Mar 08 2022 08:21:38            LOCK                            
    35352367	Mar 08 2022 13:38:19            LOG.old.1646751240613275        
481113295845	Mar 08 2022 16:19:40            001655.sst                      
 63163302913	Mar 08 2022 16:53:25            001869.sst                      
 17434582981	Mar 08 2022 16:53:13            001902.sst                      
  1157203961	Mar 08 2022 16:53:19            001904.sst                      
  1157191945	Mar 08 2022 16:53:30            001906.sst                      
  1157229408	Mar 08 2022 16:53:41            001908.sst                      
  1157173356	Mar 08 2022 16:53:52            001911.sst                      
  2131481140	Mar 08 2022 16:54:14            001912.log                      
  1157278687	Mar 08 2022 16:54:03            001913.sst                      
   242667434	Mar 08 2022 16:54:14            001915.log                      
          16	Mar 08 2022 14:54:11            CURRENT                         
          36	Mar 08 2022 08:21:38            IDENTITY                        
       28507	Mar 08 2022 16:54:15            MANIFEST-001556                 
        6290	Mar 08 2022 08:21:38            OPTIONS-000007                  
        6270	Mar 08 2022 14:54:11            OPTIONS-001559

**Comment by yhr** [comment]
@metaspace : Did you figure out why the target file size is set to 2TB? Could you reproduce the issue?

**Comment by metaspace** [comment]
Nothing to report yet.

**Comment by metaspace** [comment]
Ran the benchmark two more times with same result. It runs for 6 hours before failing.

**Comment by metaspace** [comment]
Regarding the huge file size, I fixed (my own) bug in zbdbench [here](https://github.com/westerndigitalcorporation/zbdbench/commit/704b2ae71926a9fad79df8893ad3377fb2110e86). 

However, I found an issue with `blkzone report` reporting wrong zone capacity:
```text
start: 0x000000000, len 0x400000, cap 0x400000, wptr 0x000028 reset:0 non-seq:0, zcond: 2(oi) [type: 2(SEQ_WRITE_REQUIRED)]
```
Cap should be 0x21A800 for 1077 MB zone size.

**Comment by metaspace** [comment]
> > However, I found an issue with blkzone report reporting wrong zone capacity:
> 
> Can we check if this report is not for any zoned null block devices ?

The report is for a WZS4C8T1TDSP303, (1TB ZNS). 

@floatious identified the issue in `blkzone report`. If `blkzone` is built against kernel headers that does not define `BLK_ZONE_REP_CAPACITY`, it will just report the size of the zone as the capacity. [These lines](https://github.com/util-linux/util-linux/blob/v2.37.3/sys-utils/blkzone.c#L197-L203) are the problem. I think it would make more sense if the `blkzone report` did not print the capacity field rather than printing something potentially wrong.

**Comment by floatious** [comment]
Wow, fix for blkzone merged already, nice!
